// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function GetSessionDetail(arg1:string):Promise<dto.SessionDetailResponse>;

export function Greet(arg1:string):Promise<string>;

export function ListSessions(arg1:string,arg2:number,arg3:number):Promise<Array<dto.SessionSummary>>;

export function OpenLogDirectory():Promise<void>;
