// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FrontendReady() {
  return window['go']['main']['App']['FrontendReady']();
}

export function GetLogFilePath() {
  return window['go']['main']['App']['GetLogFilePath']();
}

export function GetSessionDetail(arg1) {
  return window['go']['main']['App']['GetSessionDetail'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HandleOpenSessionFile(arg1) {
  return window['go']['main']['App']['HandleOpenSessionFile'](arg1);
}

export function ListSessions(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListSessions'](arg1, arg2, arg3);
}

export function OpenLogDirectory() {
  return window['go']['main']['App']['OpenLogDirectory']();
}

export function ResolveSessionIDFromPath(arg1) {
  return window['go']['main']['App']['ResolveSessionIDFromPath'](arg1);
}
