// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function ApplyUpdate(arg1:string):Promise<void>;

export function CheckUpdate():Promise<dto.UpdateResult>;

export function Emit(arg1:string,arg2:Array<any>):Promise<void>;

export function FrontendReady():Promise<void>;

export function GetLogFilePath():Promise<string>;

export function GetSessionDetail(arg1:string):Promise<dto.SessionDetailResponse>;

export function Greet(arg1:string):Promise<string>;

export function HandleOpenSessionFile(arg1:string):Promise<void>;

export function ListSessions(arg1:string,arg2:number,arg3:number):Promise<Array<dto.SessionSummary>>;

export function OpenLogDirectory():Promise<void>;

export function ResolveSessionIDFromPath(arg1:string):Promise<string>;
