// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeClaudeCorpus(arg1) {
  return window['go']['main']['App']['AnalyzeClaudeCorpus'](arg1);
}

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function Emit(arg1, arg2) {
  return window['go']['main']['App']['Emit'](arg1, arg2);
}

export function FrontendReady() {
  return window['go']['main']['App']['FrontendReady']();
}

export function GetLogFilePath() {
  return window['go']['main']['App']['GetLogFilePath']();
}

export function GetSessionDetail(arg1) {
  return window['go']['main']['App']['GetSessionDetail'](arg1);
}

export function GetSessionDetailByProvider(arg1, arg2) {
  return window['go']['main']['App']['GetSessionDetailByProvider'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HandleOpenSessionFile(arg1) {
  return window['go']['main']['App']['HandleOpenSessionFile'](arg1);
}

export function ListSessions(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListSessions'](arg1, arg2, arg3);
}

export function ListSessionsByProvider(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListSessionsByProvider'](arg1, arg2, arg3, arg4);
}

export function OpenLogDirectory() {
  return window['go']['main']['App']['OpenLogDirectory']();
}

export function ResolveSessionIDFromPath(arg1) {
  return window['go']['main']['App']['ResolveSessionIDFromPath'](arg1);
}

export function SaveChartImage(arg1, arg2) {
  return window['go']['main']['App']['SaveChartImage'](arg1, arg2);
}
